Bump prefetch task revision
because the current fails:

Error: UnsupportedFeature: Package manager(s) not yet supported: generic
  But the good news is that we're already working on it!