Switch fetching to go in a subdirectory instead of the repo root
For some unclear reason, fetching in the repo root makes Cachi2
upset. In StackRox we fetch into a subdirectory so I hope doing so
would help here too.

```
step-prefetch-dependencies
INFO: Using mounted CA bundle: /mnt/trusted-ca/ca-bundle.crt
'/mnt/trusted-ca/ca-bundle.crt' -> '/etc/pki/ca-trust/source/anchors/ca-bundle.crt'
2024-12-12 12:24:45,332 INFO Fetching the gomod dependencies at subpath .
2024-12-12 12:24:45,333 INFO Fetching the gomod dependencies at the "." directory
2024-12-12 12:24:49,980 INFO go.mod reported versions: '1.22'[go], '1.22.5'[toolchain]
2024-12-12 12:24:49,980 INFO Using Go release: go1.21.0
2024-12-12 12:25:13,834 INFO Downloading the gomod dependencies
/tekton/scripts/script-6-hvxlr: line 63:    41 Killed                  cachi2 --log-level="$LOG_LEVEL" $config_flag fetch-deps $dev_pacman_flag --source=/var/workdir/source --output=/var/workdir/cachi2/output "${INPUT}"
2024-12-12 12:25:52,896 ERROR InvalidInput: No .build-config.json found in /var/workdir/cachi2/output. Please use a directory populated by a previous fetch-deps command.
Error: InvalidInput: No .build-config.json found in /var/workdir/cachi2/output. Please use a directory populated by a previous fetch-deps command.
2024-12-12 12:25:53,752 ERROR InvalidInput: No .build-config.json found in /var/workdir/cachi2/output. Please use a directory populated by a previous fetch-deps command.
Error: InvalidInput: No .build-config.json found in /var/workdir/cachi2/output. Please use a directory populated by a previous fetch-deps command.
```